[package]
name = "mini-starcoin-vm"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.41"

starcoin-vm-types = {git = "https://github.com/starcoinorg/starcoin", rev = "06d5321c0dab12aef2c02ad99e9d065ba2b91774"}
starcoin-executor = {git = "https://github.com/starcoinorg/starcoin", rev = "06d5321c0dab12aef2c02ad99e9d065ba2b91774"}
starcoin-state-api = {git = "https://github.com/starcoinorg/starcoin", rev = "06d5321c0dab12aef2c02ad99e9d065ba2b91774"}
starcoin-statedb = {git = "https://github.com/starcoinorg/starcoin", rev = "06d5321c0dab12aef2c02ad99e9d065ba2b91774"}
starcoin-network-rpc-api = {git = "https://github.com/starcoinorg/starcoin", rev = "06d5321c0dab12aef2c02ad99e9d065ba2b91774"}
starcoin-state-tree = {git = "https://github.com/starcoinorg/starcoin", rev = "06d5321c0dab12aef2c02ad99e9d065ba2b91774"}
starcoin-rpc-client = {git = "https://github.com/starcoinorg/starcoin", rev = "06d5321c0dab12aef2c02ad99e9d065ba2b91774"}
starcoin-config = {git = "https://github.com/starcoinorg/starcoin", rev = "06d5321c0dab12aef2c02ad99e9d065ba2b91774"}
starcoin-types = {git = "https://github.com/starcoinorg/starcoin", rev = "06d5321c0dab12aef2c02ad99e9d065ba2b91774"}
starcoin-rpc-api = { git = "https://github.com/starcoinorg/starcoin", rev = "06d5321c0dab12aef2c02ad99e9d065ba2b91774"}
bcs-ext = { git = "https://github.com/starcoinorg/starcoin", rev = "06d5321c0dab12aef2c02ad99e9d065ba2b91774"}

starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc"}
