[package]
name = "mini-starcoin-vm"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.41"

starcoin-vm-types = {git = "https://github.com/strawWoo/starcoin", rev = "5b5b41504b65978d82c6d5f2b251b67300aba7fc"}
starcoin-executor = {git = "https://github.com/strawWoo/starcoin", rev = "5b5b41504b65978d82c6d5f2b251b67300aba7fc"}
starcoin-state-api = {git = "https://github.com/strawWoo/starcoin", rev = "5b5b41504b65978d82c6d5f2b251b67300aba7fc"}
starcoin-state-store-api = {git = "https://github.com/strawWoo/starcoin", rev = "5b5b41504b65978d82c6d5f2b251b67300aba7fc"}
starcoin-statedb = {git = "https://github.com/strawWoo/starcoin", rev = "5b5b41504b65978d82c6d5f2b251b67300aba7fc"}
starcoin-network-rpc-api = {git = "https://github.com/strawWoo/starcoin", rev = "5b5b41504b65978d82c6d5f2b251b67300aba7fc"}
starcoin-state-tree = {git = "https://github.com/strawWoo/starcoin", rev = "5b5b41504b65978d82c6d5f2b251b67300aba7fc"}
starcoin-rpc-client = {git = "https://github.com/strawWoo/starcoin", rev = "5b5b41504b65978d82c6d5f2b251b67300aba7fc"}
starcoin-config = {git = "https://github.com/strawWoo/starcoin", rev = "5b5b41504b65978d82c6d5f2b251b67300aba7fc"}
starcoin-types = {git = "https://github.com/strawWoo/starcoin", rev = "5b5b41504b65978d82c6d5f2b251b67300aba7fc"}
starcoin-rpc-api = { git = "https://github.com/strawWoo/starcoin", rev = "5b5b41504b65978d82c6d5f2b251b67300aba7fc"}
bcs-ext = { git = "https://github.com/strawWoo/starcoin", rev = "5b5b41504b65978d82c6d5f2b251b67300aba7fc"}

starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc"}
