[build]
default-target="mips64el-unknown-linux-gnuabi64"

[target.mips64el-unknown-linux-gnuabi64.env]
passthrough = [
    "RUST_BACKTRACE=1", "OPENSSL_DIR=/usr/local/ssl"
]

[target.mips64el-unknown-linux-gnuabi64]
dockerfile = "./Dockerfile"
